project:
  title: "template-computo-R"

title: "Comparative analysis of stopping criteria for multi-objective evolutionary algorithms: from benchmark problems to industrial application"
author:
  - name: Manon Perrignon
    corresponding: true
    email: manon.perrignon@institut-agro.fr
    url: 
    orcid: 0009-0007-8155-4919
    affiliations:
      - name: L’Institut Agro, INRAE, STLO (Science et Technologie du Lait et de l’œuf), Rennes, France
  - name: Magalie Houée-Bigot
    email: magalie.houee@institut-agro.fr
    url: https://pro.institut-agro-rennes-angers.fr/fr/magalie-houee-bigot
    orcid: 0009-0004-5402-4726
    affiliations: 
      - name: L’Institut Agro, Rennes, France
  - name: Romain Jeantet
    email: romain.jeantet@institut-agro.fr
    url: 
    orcid: 0000-0001-5405-5056
    affiliations: 
      - name: L’Institut Agro, INRAE, STLO (Science et Technologie du Lait et de l’œuf), Rennes, France
  - name: Thomas Croguennec
    email: thomas.croguennec@institut-agro.fr
    url: 
    orcid: 0000-0003-4720-3641
    affiliations: 
      - name: L’Institut Agro, INRAE, STLO (Science et Technologie du Lait et de l’œuf), Rennes, France
  - name: Mathieu Emily
    email: mathieu.emily@institut-agro.fr
    url: https://emily.perso.math.cnrs.fr/Homepage/index.htm
    orcid: 0000-0001-9101-6689
    affiliations: 
      - name: L’Institut Agro, Université de Rennes, CNRS, IRMAR (Institut de Recherche Mathématique de Rennes)-UMR 6625, Rennes, France
date: last-modified
date-modified: last-modified
abstract: >+
 Multi-objective optimization problems are generally solved using evolutionary algorithms. By default, the iterative algorithm stops when the number of generations set by the user is reached, which does not guarantee optimal solutions. To overcome this limitation, stopping criteria can be implemented to decide when the algorithm should stop in order to guarantee optimal solution quality. This article proposes to compare four stopping criteria known in the literature and to introduce a new one to evaluate the ideal criterion guaranteeing a balance between computation time and solution quality. To evaluate their performance, the criteria are first tested on classical multi-objective problems and then applied to an example where the optimal solutions are known and can be compared with those obtained after the implementation of the stopping criterion. Finally, the criteria will be applied to a concrete case study involving the optimisation of a food process. The aim of this comparative analysis is to identify the most appropriate criterion for reconciling the quality of solutions and computational cost.
keywords: [Multi-objective optimization, Stopping criteria, Evolutionary algorithms, Evaluation metrics, Food process optimization]
bibliography: references.bib
github-user: computorg
repo: "template-computo-r"
draft: true # set to false once the build is running
published: false # will be set to true once accepted
format:
  computo-html: default
  computo-pdf: default