project:
  title: "template-computo-R"

title: "Comparative analysis of stopping criteria for multi-objective evolutionary algorithms: from benchmark problems to industrial application"
author:
  - name: Manon Perrignon
    corresponding: true
    email: manon.perrignon@institut-agro.fr
    url: 
    orcid: 0009-0007-8155-4919
    affiliations:
      - name: L’Institut Agro, INRAE, STLO (Science et Technologie du Lait et de l’œuf), Rennes, France
  - name: Magalie Houée-Bigot
    email: magalie.houee@institut-agro.fr
    url: https://pro.institut-agro-rennes-angers.fr/fr/magalie-houee-bigot
    orcid: 0009-0004-5402-4726
    affiliations: 
      - name: L’Institut Agro, Rennes, France
  - name: Romain Jeantet
    email: romain.jeantet@institut-agro.fr
    url: 
    orcid: 0000-0001-5405-5056
    affiliations: 
      - name: L’Institut Agro, INRAE, STLO (Science et Technologie du Lait et de l’œuf), Rennes, France
  - name: Thomas Croguennec
    email: thomas.croguennec@institut-agro.fr
    url: 
    orcid: 0000-0003-4720-3641
    affiliations: 
      - name: L’Institut Agro, INRAE, STLO (Science et Technologie du Lait et de l’œuf), Rennes, France
  - name: Mathieu Emily
    corresponding: true
    email: mathieu.emily@institut-agro.fr
    url: https://emily.perso.math.cnrs.fr/Homepage/index.htm
    orcid: 0000-0001-9101-6689
    affiliations: 
      - name: L’Institut Agro, Université de Rennes, CNRS, IRMAR (Institut de Recherche Mathématique de Rennes)-UMR 6625, Rennes, France
date: last-modified
date-modified: last-modified
abstract: >+
 Multi-objective optimization problems are commonly solved using evolutionary algorithms, which typically terminate after a user-defined number of generations without guaranteeing solution optimality. Stopping criteria can address this limitation by determining when the algorithm has converged to high-quality solutions. This study compares four existing stopping criteria and proposes a novel criterion designed to balance computational cost and solution quality. The criteria are evaluated on benchmark multi-objective problems with known Pareto fronts, then applied to a food process optimization case study. Results identify the most effective criterion for achieving this trade-off in practical applications.
keywords: [Multi-objective optimization, Stopping criteria, Evolutionary algorithms, Evaluation metrics, Food process optimization]
bibliography: references.bib
github-user: computorg
repo: "template-computo-r"
draft: true # set to false once the build is running
published: false # will be set to true once accepted
format:
  computo-html: default
  computo-pdf: default